### ISSUE TITLE
Handbook: ABI inconsistency around r20

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos#131]
The handbook defines the register calling convention.

In section "4.2 Register Usage Conventions" it says: 
> * r20 through r31 are callee-saved saved registers.

However, if we look in section "2.3 Register Files" figure 2.2(a) r20 is given the label `(scratch)` as if it is caller-saved.
It clearly cannot be both.

Looking at the compiler, I can see that `PatmosRegisterInfo.cpp` defines `Patmos::R21` through `Patmos::R28` as calleesaved (in the function `PatmosRegisterInfo::getCalleeSavedRegs`).

Therefore, I suspect section 4.2 is wrong and should have r21 as the first callee-saved register.

**Comment by schoeberl** [comment]
Yes, the compiler source (and the Patmos source) are the final truth. Thanks for pointing this out. Maybe fix the handbook.

**Comment by Emoun** [comment]
fixed in 615a98811a7250fe4d7c0e6d317d0febe47b819b
