### ISSUE TITLE
Multicore devices are broken

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos#136]
Don't know when this came in, but multicore Patmos is broken :-(

We for sure should have a working CI test...

**Comment by schoeberl** [comment]
They have never been fully ported to Chisel 3 :-( Only to compile, not runtime tested (e.g., missing Wire). Now I need to do them one at a time.

**Comment by Emoun** [comment]
What is the status of getting multi-core Patmos working?

**Comment by schoeberl** [comment]
Muli-Core Patmos is working! Just not all devices have been ported.Cheers,MartinOn 29 Jan 2024, at 14.14, Emad Jacob Maroun ***@***.***> wrote:﻿
What is the status of getting multi-core Patmos working?
