### ISSUE TITLE
Generating Aegean/t-crest makes the emulator build fail

### ISSUE THREAD

**Issue by henrikh** [t-crest/patmos#16]
Running `make platform` in Aegean generates the multi-core system. A side effect is that `make emulator` fails in Patmos.

The file `patmos/hardware/emulator_config.h` is generated by the Aegean build process and makes the build fail by taking precedence over the correct configuration file (in `patmos/hardware/build/`).

The configuration file is generated by `patmos/hardware/src/patmos/Config.scala` at line 254. The patmos generation is for some reason run with the cpp backend, but without a configured memory. This messes up the generated configuration header.

Work around: Delete `patmos/hardware/emulator_config.h` and run `make emulator`

**Comment by schoeberl** [comment]
Maybe the best fix would be that the Aegean generation would do the cleanup and remove that .h file after build.

Cheers,
Martin

**Comment by henrikh** [comment]
I dug some more into it today and I have found the cause and a possible solution. The check for which backend is used is run before the backend has been determined.

In `patmos/hardware/src/patmos/Patmos.scala`:

```Scala
Config.loadConfig(configFile, backend)
[...]
chiselMain(chiselArgs, () => Module(new PatmosCore(binFile)))
```

`loadConfig` is responsible for generating `emulator_config.h`. This is done by checking the backend:
```Scala
if (Driver.backend.isInstanceOf[CppBackend]) {
  val emuConfig = Driver.createOutputFile("emulator_config.h")
  [...]
}
```
Here comes the catch. `Driver.backend` is first set when running `chiselMain`, which will only happen later in `Patmos.scala`.

A solution would be to parse the command line arguments before `chiselMain` or to figure out if header generation could run after `chiselMain`.

**Comment by schoeberl** [comment]
As a work-around for the time being delete `emulator_config.h` in the folder `t-crest/patmos/hardware/build` and the correct one will be generated when building the emulator from within the Patmos source tree.

We will solve this issue when we have a Chisel top component for the multicore version of Patmos. Hopefully soon.

**Comment by schoeberl** [comment]
Within Patmos a `make clean` will remove the offending left over. Still a workaround until the Chisel top level.

**Comment by schoeberl** [comment]
As of today, we will not use Aegean anymore. It is substituted by a Chisel based wrapper. Solved the issue.
