### ISSUE TITLE
pasim: doesn't take predicates into account when complaining about use of load without delay slot

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos#40]
The `pasim` simulator does not take predicates into account when it throws an error about use of load value without a delay slot.

Take this assembly program:
```
	.file	"main.bc"
	.text
	.globl	main
	.align	16
	.type	main,@function
	.fstart	main, .Ltmp0-main, 16
main:                                        # @main
# BB#0:                                      # %entry
        sres 8
        mfs $r9 = $s0
        sws [1] = $r9            # 4-byte Folded Spill
        sws [2] = $r26           # 4-byte Folded Spill
        li $r1 = main
        lwc $r2 = [$r1]      #Load of r2
  (!$p0)add $r1 = $r1, $r2   #Use of r2, throws error
        mov $r1 = $r0
        lws $r9 = [1]            # 4-byte Folded Reload
        ret	
        lws $r26 = [2]           # 4-byte Folded Reload
        mts $s0 = $r9
        sfree 8
.Ltmp0:
.Ltmp1:
	.size	main, .Ltmp1-main
```
Compiling and running the program with `pasim` will make it throw the following error:
```
Cycle 24502: Illegal instruction at 00052048<main + 0x24>: Use of load result without delay slot!
Stacktrace:
#0 0x52024 <main>(): $rsp 0x68 stack cache size 0x40
   at 0x52048 (base: 0x52024 <main>, offset: 0x24 <main + 0x24>)
#1 0x20124 <__start>(): $rsp 0x7fffffff stack cache size 0x0
   at 0x201cc (base: 0x20194 <__start:.LBB1_1:.Ltmp2 + 0x8>, offset: 0x38 <__start:.LBB1_1:.Ltmp2 + 0x40>)
#2 0x20084 <_start>(): $rsp 0x7fffffff stack cache size 0x0
   at 0x20110 (base: 0x20084 <.LBB0_0:_start>, offset: 0x8c <_start + 0x8c>)
```
The offending instruction is `(!$p0)add $r1 = $r1, $r2`. `pasim`'s error does not point directly to it, but to the subsequent instruction. We can remove the error by introducing a `nop` between the load and the use:
```
	.file	"main.bc"
	.text
	.globl	main
	.align	16
	.type	main,@function
	.fstart	main, .Ltmp0-main, 16
main:                                        # @main
# BB#0:                                      # %entry
        sres 8
        mfs $r9 = $s0
        sws [1] = $r9            # 4-byte Folded Spill
        sws [2] = $r26           # 4-byte Folded Spill
        li $r1 = main
        lwc $r2 = [$r1]     #Load of r2
        nop
  (!$p0)add $r1 = $r1, $r2  #Use of r2, doesn't throw an error
        mov $r1 = $r0
        lws $r9 = [1]            # 4-byte Folded Reload
        ret	
        lws $r26 = [2]           # 4-byte Folded Reload
        mts $s0 = $r9
        sfree 8
.Ltmp0:
.Ltmp1:
	.size	main, .Ltmp1-main
```
Usually, this error is correct, because the load instructions have 1 load-to-use latency where the destination register does not have the loaded value. But, in our case, the use instruction is predicated, and we can see that it will never run. In this case we can even see it before running the program, since (!$p0) is always false. But, the predicate could also be run-time-dependent.
In my mind, `pasim` should check the value of the predicate before throwing this error, such that if the predicate evaluates to false, at run-time, the error is not thrown. 

Am I totally off in my understanding of the instruction set and `pasim` or should this be fixed?

**Comment by schoeberl** [comment]
If you predicate the use of a register load with a predicate the *can* be true, then the error is a real one, right? So I think pasim is fine. Predicating and instruction to never be true would be more clear to be a nop. In that case I would not blaim pasim to raise a false positive error.

**Comment by Emoun** [comment]
But `pasim` doesn't predict, it executes, no? which means we should be able to just read the predicate register and see if the instruction should be run. I have looked at its code, and as far as I can tell the data hazard check is done at run-time, so the info should be there.

**Comment by schoeberl** [comment]
I still do not see the use case of having a predicated use instruction just after the load that needs a load/use delay slot. Can you elaborate on the use case here?

Martin
