### ISSUE TITLE
Hard coded IO constants

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos#45]
Change all hardcoded constants in the C files to use the defined ones from machine/patmos.h

**Comment by egk696** [comment]
What do I do regarding new devices such as the 7segment (io/SevenSegment.scala) and the GPIO (io/Gpio.scala) ? Should I add them to patmos.h or leave them for now as constants ?

**Comment by schoeberl** [comment]
Add them to patmos.h.

Martin

**Comment by schoeberl** [comment]
There are still quite some hardcode constants left. Find them with ```ag 0xf0```

**Comment by egk696** [comment]
Thanks about the command, it proved to be useful. 

I fixed most hard-coded IO constants however some need special attention as they are not common devices of the _altde2-all_ configuration. These are:
- apps/de10-nano/blinking.c
- apps/de10-nano/hello_MPU6050.c
- apps/de10-nano/acts_props_uart2.c
- libsd/sd_spi.c

In some cases e.g. apps/de10-nano/hello_MPU6050.c
`12:#define I2C ( *( ( volatile _IODEV unsigned * )      0xF00C0000 ) )`
The address collides with the `PATMOS_IO_AUDIO`, what should we do in this case? Should I add just a I2C device in patmos.h with the same address as AUDIO? Is I2C in a fully functional state?

**Comment by schoeberl** [comment]
The I2C works. Please assign a new, unique address to the i2c device and change the example accordingly.

Martin

**Comment by egk696** [comment]
Should I also add something called MPU ? If add this also then we run out of address space: 
```
#define PATMOS_IO_CPUINFO  0xf0000000
#define PATMOS_IO_EXCUNIT  0xf0010000
#define PATMOS_IO_TIMER    0xf0020000
#define PATMOS_IO_DEADLINE 0xf0030000
#define PATMOS_IO_GPIO     0xf0040000
#define PATMOS_IO_SEGDISP  0xf0050000
#define PATMOS_IO_UART2    0xf0060000
#define PATMOS_IO_UART3    0xf0070000
#define PATMOS_IO_UART     0xf0080000
#define PATMOS_IO_LED      0xf0090000
#define PATMOS_IO_KEYS     0xf00a0000
#define PATIOS_IO_I2C      0xf00b0000
#define PATMOS_IO_AUDIO    0xf00c0000
#define PATMOS_IO_ETH      0xf00d0000
#define PATMOS_IO_ETH1     0xf00e0000
#define PATMOS_IO_SD       0xf00f0000
```
I think we should not add the MPU as it is not a real "interface". Also something must be done with the multiple UARTS, maybe they could be combined.

Cheers,
Lefteris

**Comment by schoeberl** [comment]
Yes, please add an MPU.

I assume we can use more than 4 bits for address decoding ;-) But this needs to be checked in the Patmos source.

Agree that the UARTs are a mess. First, because of source copy (very, very bad, I did it) and second they should probably be all in one address space. But this is another TODO/issue ;-)

Cheers,
Martin
