### ISSUE TITLE
Split off simulator into its own repo

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos#60]
I think we should extract the simulator (everything under `patmos/simulator`) into its own repository under t-crest.

I need this to make a good automatic testing and deployment setup using github and travis-ci. This is because we currently have a circular dependency in our repositories:
To build and test LLVM, we need `pasim`, however, to build and test Patmos (which contains `pasim`), we need LLVM. However, the simulator on its own is not dependent on LLVM, which means if we extract it, we can build it independently and then use it for the LLVM build.

I have already tested that the `simulator` folder is completely self-contained and can simply be extracted from the patmos repository. However, I do not have permission to make new t-crest repositories, so I need someone who can do this for me.

**Comment by schoeberl** [comment]
Ok, I created the repo. Feel free to move pasim over.

Martin

**Comment by Emoun** [comment]
Thank you. I probably won't delete the simulator from this repo immediately, since I'll need to edit patmos-misc to use the new repo. We just have to make sure no one updates the simulator in this repo any more.

**Comment by schoeberl** [comment]
Hi Emad,

I hope we do not have a copy of the simulator in both places, right?

Martin

**Comment by Emoun** [comment]
The plan is for the only copy to reside in the new repo. However, I will need to update our setup make use of the new repo. So, I will keep the copy in this repo until the setup is updated.

**Comment by schoeberl** [comment]
I think we need to discuss this a bit more (and maybe others should jump in here as well, Torur?). The original issue is a build dependency and not a repository dependency. And pasim/pasasm can be built completely independent of Patmos. So we just need to do this, right?

There are two reasons that are against the split: (1) we lose all the commit history in the new repo. It looks like @Emoun would be the sole author and not Florian. (2) Core Patmos and core tests depend on paasm. I would like to keep that assembler close. So one can do some base sanety checking of Patmos without dependency on another repository.

**Comment by Emoun** [comment]
Regarding (1):

Losing commit history is of course a downside, but staying in Patmos also means that the future commit history is jumbled with the rest of the patmos history (as is the current pasim history). So moving pasim to its own repo gives us a better history moving forward.

Alternatively, I could redo the move, and instead of copying the code and commiting it myself, I could copy the whole git repo over and then remove everything that isn't pasim in one commit. This would keep the history. Maybe this is acceptable? This would also solve the issue with giving me credit for other's work.

(2) I think we can minimize the complexity of depending on another repo. This needs to be done for LLVM anyway, since you can't test that without pasim. My current goal is prebuilt binaries that can simply be downloaded from Github Releases without needing to build it on your own. This is already implemented and working. A future possibility is making ubuntu packages, such that it's almost trivial to install `pasim`, `paasm`, etc.

Having more focused repositories also gives us much more flexibility with CI, as the total allowed build/test time scales with the number of repositories. Additionally, it is easier to manage issues and PRs, as you can now more easily see which tool they are about.

**Comment by Emoun** [comment]
Mistakenly closed the issue. Reopened.

**Comment by henrikh** [comment]
I can try to look into extracting the history of the pasim folder from the repository. It is possible to extract folders and preserve all history and all comitters: https://help.github.com/en/github/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by Emoun** [comment]
I have now redone the copy of the simulator using the method @henrikh mentioned (thanks for the link @henrikh). This has now preserved the history of the simulator, and filtered out any commit that didn't touch it.
