### ISSUE TITLE
Argo is not working after recent chain of commits

### ISSUE THREAD

**Issue by egk696** [t-crest/patmos#62]
Using bisect I worked my way to a working commit for Argo and that seems to be titled:
[chisel3: Last bug that i can resolve for compatability layer. Regtest… ](https://github.com/t-crest/patmos/commit/baaa205c7d5c951613394105b57531f2a0c0d9ea)

I have tried looking through the changes to find what could possibly break Argo but I cannot, so I am opening an issue.

**Comment by schoeberl** [comment]
Ok, this commit is the last one that worked? Or the one that broke it?
If so we need to look at the last one that breaks Argo.

**Comment by egk696** [comment]
The following is output is from my recent bisect:

git bisect start
# bad: [5f0493c70c7ac518c38b7444066619a01854ad21] tte producer consumer demo (WIP) and added debug gpios to top-level
git bisect bad 5f0493c70c7ac518c38b7444066619a01854ad21
# good: [baaa205c7d5c951613394105b57531f2a0c0d9ea] chisel3: Last bug that i can resolve for compatability layer. Regtest was run without introducing new errors
git bisect good baaa205c7d5c951613394105b57531f2a0c0d9ea
# good: [baaa205c7d5c951613394105b57531f2a0c0d9ea] chisel3: Last bug that i can resolve for compatability layer. Regtest was run without introducing new errors
git bisect good baaa205c7d5c951613394105b57531f2a0c0d9ea
# bad: [ef35c04d21081c302efafa8b5dd098d312528199] Chisel3: Data should be the superclass of Node.
git bisect bad ef35c04d21081c302efafa8b5dd098d312528199
# bad: [52dc8b6399498874aab6768ff33bcaf67e8bb316] Chisel3 changed to scala/java print
git bisect bad 52dc8b6399498874aab6768ff33bcaf67e8bb316
# bad: [ec4dd5350a49e0cd599cb6388a03c3a1c4c298ea] Chisel3: Has overwritten the printf function to ease chisel specific prints.
git bisect bad ec4dd5350a49e0cd599cb6388a03c3a1c4c298ea
# bad: [2907388a6ec981995a6a025b30745a1def03a517] Chisel3: throws error when black boxes are used.
git bisect bad 2907388a6ec981995a6a025b30745a1def03a517
# bad: [2907388a6ec981995a6a025b30745a1def03a517] Chisel3: throws error when black boxes are used.
git bisect bad 2907388a6ec981995a6a025b30745a1def03a517
# good: [8451394be3c2c29180e4b22f551447375bbe7b44] Chisel3: changed to UInt as Chisel3 doenst support bitwise operators on Bits
git bisect good 8451394be3c2c29180e4b22f551447375bbe7b44
# first bad commit: [2907388a6ec981995a6a025b30745a1def03a517] Chisel3: throws error when black boxes are used.

**Comment by schoeberl** [comment]
From the log, I see following commit breaking: 2907388 <https://github.com/t-crest/patmos/commit/2907388a6ec981995a6a025b30745a1def03a517>

That one of course, as it drops the black box support.

Martin

**Comment by egk696** [comment]
After a new more thorough bisect I end up here:
patmos@ubuntu:~/t-crest/patmos$ git bisect bad
ad5eea57381d8aeb9cb0403729bd440f85e94f01 is the first bad commit
commit ad5eea57381d8aeb9cb0403729bd440f85e94f01
Author: Tórur Biskopstø Strøm <torur.strom@gmail.com>
Date:   Thu Jan 9 15:18:22 2020 +0100

    iostreamline: Removed InOut and moved content to top

:040000 040000 e89a2aa23c30ce278bb0060c55785e965fe14bd5 2666ee35b14a34e93e9957f25052a034fb01fbe5 M      hardware

**Comment by torurstrom** [comment]
This was fixed with our latest changes, right?

**Comment by egk696** [comment]
Yes this is fixed
