### ISSUE TITLE
XML parameter config for onboard memory issue

### ISSUE THREAD

**Issue by cgkiokas** [t-crest/patmos#68]
In Config.scala (line 244) we now force that in every _ExtMem_ device there must be an _sramAddrWidth_ param:
 ```scala    
      if (!(ExtMemNode \ "@DevTypeRef").isEmpty){
        ExtMemDev = devFromXML(ExtMemNode,DevList,false)
        ExtMemAddrWidth = ExtMemDev.params("sramAddrWidth")
      }
```
However, if an onboard memory is used it creates the awkward situation of needing double address width parameters, otherwise the build of course fails with a key not found error: 
```xml
  <Dev DevType="OCRam" entity="OCRamCtrl" iface="OcpBurst">
     <params>
        <param name="addrWidth" value="19" />
        <param name="sramAddrWidth" value="19" />
     </params>
   </Dev>
```

**Comment by schoeberl** [comment]
An on-chip SRAM "simulation" is anyway a bit strange. What about the OCRam using sramAddrWidth instead of its own addrWidth parameter?
