### ISSUE TITLE
printout of Configuration

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos#76]
Utility.printConfig(configFile) needs an update, commented out in Patmos.scala

**Comment by Thonner** [comment]
Yes. Chisel 3 have overridden some of Scala's print functions. I can look into it!

**Comment by schoeberl** [comment]
I guess this was not a very good idea to overload such a useful function! You can use string interpolation and println instead.

Martin

**Comment by Thonner** [comment]
printConfig has been rewritten to use println in commit:
https://github.com/t-crest/patmos/commit/da898cc8cbe2507ef4c363690ab597d80c5ff34f
