### ISSUE TITLE
Yahoo is shutting down their mailing list

### ISSUE THREAD

**Issue by schoeberl** [t-crest/patmos#78]
We use Yahoo for the Patmos mailing list. We need to move soon. And all the history is lost :-(

**Comment by henrikh** [comment]
Will it continue to be a mailing list (which _is_ nice and simple) or are you considering a forum?

**Comment by schoeberl** [comment]
No, it will sadly shut down all mailing lists. Guess, we need to move to Google groups.

Martin

**Comment by schoeberl** [comment]
We have moved to Google Groups. Please register here: https://groups.google.com/g/patmos-processor

Cheers,
Martin
